publish_to: 'none'

name: logos_dashboard
version: 0.1.0

description: Configure, manage and monitor Logos on your communities.

homepage: https://github.com/vxern/logos_dashboard
repository: https://github.com/vxern/logos_dashboard
issue_tracker: https://github.com/vxern/logos_dashboard/issues

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_color: ^2.1.0
  flutter_form_builder: ^9.3.0
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.2.1
  material_symbols_icons: ^4.2771.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  words: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/localisations/

flutter_launcher_icons:
  ios: true
  image_path: assets/icons/logo.png
  remove_alpha_ios: true
  web:
    generate: true
  macos:
    generate: true
