publish_to: 'none'

name: logos_dashboard
version: 0.1.0

description: Configure, manage and monitor Logos on your communities.

homepage: https://github.com/vxern/logos_dashboard
repository: https://github.com/vxern/logos_dashboard
issue_tracker: https://github.com/vxern/logos_dashboard/issues

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  go_router: ^14.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  words: ^0.5.0

flutter:
  uses-material-design: true
