publish_to: 'none'

name: logos_dashboard
version: 0.1.0

description: Configure, manage and monitor Logos on your communities.

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
