publish_to: 'none'

name: logos_dashboard
version: 0.1.0

description: Configure, manage and monitor Logos on your communities.

homepage: https://github.com/vxern/logos_dashboard
repository: https://github.com/vxern/logos_dashboard
issue_tracker: https://github.com/vxern/logos_dashboard/issues

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_web_plugins:
    sdk: flutter
  gap: ^3.0.1
  go_router: ^14.2.1
  material_symbols_icons: ^4.2771.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  words: ^0.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/localisations/
